osx_image: xcode12.5.1
language: swift
os: osx
xcode_project: Halo.xcodeproj
xcode_scheme: Halo
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 8

before_install: rvm use $RVM_RUBY_VERSION
install: bundle install --without=documentation --path ../travis_bundle_dir
after_success: slather
